{% set name = "arbol" %}
{% set version = "2026.2.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arbol-{{ version }}.tar.gz
  sha256: 6ec531f8f3b06283da0471d4e351ff195f79709d5ab2d71a59c4275b29219d43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}.*
  run:
    - python >={{ python_min }}

test:
  imports:
    - arbol
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/royerlab/arbol
  summary: arbol -- Arborescent Printouts in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - royerloic
