{% set name = "arbol" %}
{% set version = "2026.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arbol-{{ version }}.tar.gz
  sha256: 010047f6e6b62eae245ca029974aecb33ae8c2a23396c0334c4d5caa5322e247

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - arbol
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/royerlab/arbol
  summary: arbol -- Arborescent Printouts in Python
  license: BSD-3-Clause OR MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
