{% set name = "arbol" %}
{% set version = "2025.2.27.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arbol-{{ version }}.tar.gz
  sha256: ebd85cec441be3125a1b830bb1b912892e3341bf2d2523c6f82de9850f63c546

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - arbol
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/royerlab/arbol
  summary: arbol -- Arborescent Printouts in Python
  license: BSD-3-Clause OR MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
